#if !canImport(ObjectiveC)
import XCTest

extension NIOAsyncTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NIOAsyncTests = [
        ("testAsync", testAsync),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NIOAsyncTests.__allTests__NIOAsyncTests),
    ]
}
#endif
