name: test
on: [push]
jobs:
  macOS:
    runs-on: 
      macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build
    - name: Run Tests
      run: swift test --sanitize=thread
    - name: Performance Tests
      run: swift test -c release
#   bionic:
#     container: 
#       image: swift:5.1-bionic
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Build
#       run: swift build
#     - name: Test 
#       run: swift test --sanitize=thread
